version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 30
        type: pull_request
    pass:
      - do: comment
        payload:
          body: This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.
      - do: labels
        add: 'Stale'

  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: or
        validate:
          - do: title
            must_include:
              regex: '\[(DEVO|RND|CP|DP|DS|CR)-\d+\]|\[SRE\]|\[DEVOPS\]'
    pass:
      - do: labels
        add: 'Ready for Review'
      - do: checks
        status: 'success'